name: complaint service CI

on: 
  push:
    branches: [ "master" ]
  

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: setup jdk
      uses: actions/setup-java@v3.5.0
      with:
        java-version: '18'
        distribution: 'temurin'
        
    - name: build with maven
      run:
        mvn clean install package
    - name: Docker login  
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: build docker image and push to docker hub 
      run: |
        docker build . -t ${{secrets.DOCKER_USER}}/complaint-service:${{github.sha}}
        docker push ${{ secrets.DOCKER_USER }}/domain-header:${{ github.sha }}
    - name: announce the eeeeend
      run: echo "the eneeeeeeed"
          
        
        
        
